name: CI to Docker Hub

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2
        
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
        
#      - name: Bump release version
#        id: bump_version
#        uses: christian-draeger/increment-semantic-version@1.0.2
#        with:
#         current-version: '1.0.0'
#          version-fragment: 'bug'

      - name: Build with Maven
        run: |
          mvn -B package --file my-app/pom.xml
          mkdir staging && cp target/*.jar staging
       
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: staging
        
        
        
        
        
        
        
        
        
        

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/maven-hello-world:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
